[package]
name = "kayak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
colored = "2"
pep440 = "0.2.0"
python-pkginfo = "0.5.5"
regex = "1.8.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tempfile = "3.5.0"
trove-classifiers = "0.1.0"
ureq = { version = "2.6.2", features = ["json"] }
url = "2.3.1"
zip = "0.6.4"
